<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:include schemaLocation="gxbasic.xsd"/>
  <xs:element name="ExportFile">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="KMW"/>
        <xs:element ref="Source"/>
        <xs:element ref="Actions"/>
        <xs:element ref="Objects"/>
        <xs:element ref="Attributes"/>
        <xs:element ref="Dependencies"/>
        <xs:element ref="ObjectsIdentityMapping"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Actions">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Objects">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Object"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Object" >
  	<xs:complexContent>
  		<xs:extension base="Object">
			<!-- Data Provider -->
 	 		<xs:attribute name="type" fixed="2a9e9aba-d2de-4801-ae7f-5e3819222daf"></xs:attribute>
  		</xs:extension>
  	</xs:complexContent>
  </xs:element>
  <xs:element name="Part">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="Help"/>
          <xs:element ref="Source"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="Variable"/>
        </xs:choice>
        <xs:element ref="Properties"/>
      </xs:sequence>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Variable">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Documentation"/>
        <xs:element ref="Help"/>
        <xs:element ref="Properties"/>
      </xs:sequence>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Documentation">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Attributes">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Help">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="HelpItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="HelpItem">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Language"/>
        <xs:element ref="Content"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Language" type="xs:string"/>
  <xs:element name="Content">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Properties">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Property"/>
      </xs:sequence>
      <xs:attribute name="Name"/>
      <xs:attribute name="PackageName" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Property">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name" type="xs:NCName"/>
  <xs:element name="Value" type="xs:anyURI"/>
</xs:schema>
