<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:include schemaLocation="gxbasic.xsd"/>
  <xs:element name="ExportFile">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="KMW"/>
        <xs:element ref="Source"/>
        <xs:element ref="Actions"/>
        <xs:element ref="Objects"/>
        <xs:element ref="Attributes"/>
        <xs:element ref="Dependencies"/>
        <xs:element ref="ObjectsIdentityMapping"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Actions">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Objects">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Object"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Object" >
  	<xs:complexContent>
  		<xs:extension base="Object">
			<!-- Image -->
 	 		<xs:attribute name="type" fixed="9fb193d9-64a4-4d30-b129-ff7c76830f7e"></xs:attribute>
  		</xs:extension>
  	</xs:complexContent>
  </xs:element>
  <xs:element name="Part">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Images"/>
        <xs:element ref="Properties"/>
      </xs:sequence>
      <xs:attribute name="type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Images">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ImageItem"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ImageItem">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Image"/>
        <xs:element ref="Properties"/>
        <xs:element minOccurs="0" ref="ThemeReference"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Image">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Data"/>
      </xs:sequence>
      <xs:attribute name="description" use="required"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Data">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="base64Binary"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="base64Binary" type="xs:base64Binary"/>
  <xs:element name="ThemeReference" type="xs:string"/>
  <xs:element name="Attributes">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Properties">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Property"/>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:NCName"/>
      <xs:attribute name="PackageName" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Property">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name" type="xs:NCName"/>
  <xs:element name="Value" type="xs:string"/>
</xs:schema>
